name: CI

on:
    push:
        branches:
            - 'release'

jobs:
    main:
        name: Publish

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Use Node 16.x
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x
                  cache: yarn

            - run: yarn install
            - run: yarn run build
            - run: yarn run export
            - run: touch ./out/.nojekyll

            - name: deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./out
